defmodule ExPolygon.Financial do
  @type t :: %ExPolygon.Financial{}

  defstruct ~w(
    ticker
    period
    calendar_date
    report_period
    updated
    accumulated_other_comprehensive_income
    assets
    assets_average
    assets_current
    asset_turnover
    assets_non_current
    book_value_per_share
    capital_expenditure
    cash_and_equivalents
    cash_and_equivalents_usd
    cost_of_revenue
    consolidated_income
    current_ratio
    debt_to_equity_ratio
    debt
    debt_current
    debt_non_current
    debt_usd
    deferred_revenue
    depreciation_amortization_and_accretion
    deposits
    dividend_yield
    dividends_per_basic_common_share
    earning_before_interest_taxes
    earnings_before_interest_taxes_depreciation_amortization
    ebitda_margin
    earnings_before_interest_taxes_depreciation_amortization_usd
    earning_before_interest_taxes_usd
    earnings_before_tax
    earnings_per_basic_share
    earnings_per_diluted_share
    earnings_per_basic_share_usd
    shareholders_equity
    average_equity
    shareholders_equity_usd
    enterprise_value
    enterprise_value_over_ebit
    enterprise_value_over_ebitda
    free_cash_flow
    free_cash_flow_per_share
    foreign_currency_usd_exchange_rate
    gross_profit
    gross_margin
    goodwill_and_intangible_assets
    interest_expense
    invested_capital
    invested_capital_average
    inventory
    investments
    investments_current
    investments_non_current
    total_liabilities
    current_liabilities
    liabilities_non_current
    market_capitalization
    net_cash_flow
    net_cash_flow_business_acquisitions_disposals
    issuance_equity_shares
    issuance_debt_securities
    payment_dividends_other_cash_distributions
    net_cash_flow_from_financing
    net_cash_flow_from_investing
    net_cash_flow_investment_acquisitions_disposals
    net_cash_flow_from_operations
    effect_of_exchange_rate_changes_on_cash
    net_income
    net_income_common_stock
    net_income_common_stock_usd
    net_loss_income_from_discontinued_operations
    net_income_to_non_controlling_interests
    profit_margin
    operating_expenses
    operating_income
    trade_and_non_trade_payables
    payout_ratio
    price_to_book_value
    price_earnings
    price_to_earnings_ratio
    property_plant_equipment_net
    preferred_dividends_income_statement_impact
    share_price_adjusted_close
    price_sales
    price_to_sales_ratio
    trade_and_non_trade_receivables
    accumulated_retained_earnings_deficit
    revenues
    revenues_usd
    research_and_development_expense
    return_on_average_assets
    return_on_average_equity
    return_on_invested_capital
    return_on_sales
    sales_per_share
    share_based_compensation
    selling_general_and_administrative_expense
    share_factor
    shares
    tangible_asset_value
    tax_assets
    income_tax_expense
    tax_liabilities
    tangible_assets_book_value_per_share
    weighted_average_shares
    weighted_average_shares_diluted
    working_capital
  )a
end
